import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Cairo } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure the Cairo font
const cairo = Cairo({
  subsets: ['arabic', 'latin'], // Include necessary subsets
  weight: ['400', '700'], // Specify weights you need
  variable: '--font-cairo', // Optional: CSS variable for custom usage
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${cairo.className} antialiased`}
      >

        <Navbar/>
        
        {children}
        <Footer/>
      </body>
    </html>
  );
}
